In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from tqdm.notebook import tqdm

In [2]:
cd ..

/ewsc/exxact04/vshir/tcga

In [3]:
labelled_data = pd.read_pickle('pkl/GI_cluster50_labelled_all_mar28.pkl') #dataframe containing the cluster labels for each coordinate 
labelled_data.head()

                                                          label     X      Y
paad TCGA-HZ-A9TJ-01Z-00-DX1.CB2953B6-9601-4300-BC89... 0     0  1792  11264
                                                        1     0  1792  11520
                                                        2    46  2048   9984
                                                        3    46  2048  10240
                                                        4    46  2048  10496

In [4]:
pairwise_slide = pd.read_pickle('pkl/cluster_50_pairwise_slide_03_31_26.pkl') 
pairwise_slide.head()

,cancer_type,tcga_id,cluster 1,cluster 2,contact count,total_c1_interactions,frequency
0,coad,TCGA-AA-3553-01Z-00-DX1.45a24cd4-6eb2-4f20-945...,3,4,8825,9368,0.942037
1,coad,TCGA-AA-3553-01Z-00-DX1.45a24cd4-6eb2-4f20-945...,3,34,543,9368,0.057963
2,coad,TCGA-AA-3553-01Z-00-DX1.45a24cd4-6eb2-4f20-945...,4,34,108,8933,0.012090
3,coad,TCGA-AA-3695-01Z-00-DX1.be93a101-7b57-4140-bd8...,3,4,16012,17216,0.930065
4,coad,TCGA-AA-3695-01Z-00-DX1.be93a101-7b57-4140-bd8...,3,13,8,17216,0.000465

In [5]:
pairwise_freq = pd.read_pickle('pkl/cluster_50_freq.pkl') 
pairwise_freq.head()

label,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
tcga_id,,,,,,,,,,,,,,,,,,,,,
TCGA-05-4244-01Z-00-DX1.d4ff32cd-38cf-40ea-8213-45c2b100ac01,0.0,0.000000,0.000434,0.626020,0.297290,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.009727,0.0,0.021626,0.001042,0.000000,0.0
TCGA-05-4245-01Z-00-DX1.36ff5403-d4bb-4415-b2c5-7c750d655cde,0.0,0.000256,0.060548,0.484639,0.302867,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.018689,0.0,0.016641,0.000128,0.003840,0.0
TCGA-05-4249-01Z-00-DX1.9fce0297-cc19-4c04-872c-4466ee4024db,0.0,0.000000,0.000307,0.712273,0.119353,0.0,0.000256,0.0,0.0,0.0,...,0.0,0.000000,0.000051,0.0,0.000000,0.0,0.016136,0.000051,0.002356,0.0
TCGA-05-4250-01Z-00-DX1.90f67fdf-dff9-46ca-af71-0978d7c221ba,0.0,0.000065,0.001821,0.581686,0.319199,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000065,0.000000,0.0,0.000260,0.0,0.010731,0.000976,0.000976,0.0
TCGA-05-4382-01Z-00-DX1.76b49a4c-dbbb-48b0-b677-6d3037e5ce88,0.0,0.000551,0.001652,0.648234,0.182333,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000079,0.000000,0.0,0.004248,0.0,0.047589,0.005192,0.000315,0.0

In [6]:
labelled_data = labelled_data.loc[['esca','coad','paad','stad','read']]
labelled_data

                                                              label      X  \
esca TCGA-2H-A9GF-01Z-00-DX1.FA1016AF-3FE3-45DC-A77B... 0        13   4352
                                                        1        32   4352
                                                        2        32   4352
                                                        3        47   4608
                                                        4        48   4608
...                                                             ...    ...
read TCGA-F5-6861-01Z-00-DX1.011B771B-F52E-412E-9352... 36609    13  94208
                                                        36610    29  94208
                                                        36611    29  94208
                                                        36612    13  94208
                                                        36613    13  94208

                                                                   Y
esca TCGA-2H-A9GF-01Z-00-DX1.FA1016AF-3FE3-45DC-A77B... 0      63232
                                                        1      63488
                                                        2      63744
                                                        3      61952
                                                        4      62208
...                                                              ...
read TCGA-F5-6861-01Z-00-DX1.011B771B-F52E-412E-9352... 36609  20736
                                                        36610  20992
                                                        36611  21248
                                                        36612  21504
                                                        36613  21760

[58780353 rows x 3 columns]

In [7]:
all_slide_ids = pd.read_pickle('pkl/GI_allslide_IDs_mar28.pkl') #dataframe with all the slide IDs 
cancer_types = ['paad','coad','esca','stad','read']
all_slide_ids

paad  0      TCGA-HZ-A9TJ-01Z-00-DX1.CB2953B6-9601-4300-BC8...
      1      TCGA-IB-A5SP-01Z-00-DX1.0D3C9A7E-F73C-4F03-98C...
      2      TCGA-2L-AAQL-01Z-00-DX1.641D4EA1-ABC9-4121-BB2...
      3      TCGA-HV-A7OP-01Z-00-DX1.9DCA3D26-8093-4D09-AE2...
      4      TCGA-2L-AAQE-01Z-00-DX1.5D60E31B-9E39-4472-837...
                                   ...
read  153    TCGA-AG-4007-01Z-00-DX1.1344292e-78ad-4db8-b03...
      154    TCGA-F5-6864-01Z-00-DX1.95556dfa-18a9-4a59-a1f...
      155    TCGA-AG-4001-01Z-00-DX1.1dbafe58-de6b-47a0-9b4...
      156    TCGA-G5-6641-01Z-00-DX1.5d9d937f-0e87-4cdb-87f...
      157    TCGA-F5-6861-01Z-00-DX1.011B771B-F52E-412E-935...
Length: 1841, dtype: object

In [8]:
short_ids = all_slide_ids.str[:12] 
short_ids

paad  0      TCGA-HZ-A9TJ
      1      TCGA-IB-A5SP
      2      TCGA-2L-AAQL
      3      TCGA-HV-A7OP
      4      TCGA-2L-AAQE
                 ...
read  153    TCGA-AG-4007
      154    TCGA-F5-6864
      155    TCGA-AG-4001
      156    TCGA-G5-6641
      157    TCGA-F5-6861
Length: 1841, dtype: object

In [76]:
cancer_type = 'esca'
cancer_type_list = ['coad', 'esca', 'paad', 'stad', 'read'] 
cn_1 = 8
cn_2 = 11

In [77]:
filtered_df = pairwise_slide[(pairwise_slide['cancer_type']==cancer_type) & (pairwise_slide['cluster 1']==cn_1) & (pairwise_slide['cluster 2']==cn_2)] #return dataframe for the cluster pair of interest 
filtered_df

,cancer_type,tcga_id,cluster 1,cluster 2,contact count,total_c1_interactions,frequency
78065,esca,TCGA-IG-A625-01Z-00-DX1.48DC96DA-6573-4AA3-898...,8,11,2487,38355,0.064842
78742,esca,TCGA-JY-A93F-01Z-00-DX1.8DCF766B-0B3F-4B4C-8FD...,8,11,29,16766,0.001730
79448,esca,TCGA-IG-A50L-01Z-00-DX1.25755523-4D42-4377-B05...,8,11,1362,38037,0.035807
80155,esca,TCGA-LN-A49M-01Z-00-DX1.3D8240BD-2689-4CBB-83E...,8,11,2,432,0.004630
80917,esca,TCGA-JY-A93E-01Z-00-DX1.ECCA983B-C9EE-4074-A28...,8,11,14944,42278,0.353470
81532,esca,TCGA-ZR-A9CJ-01Z-00-DX1.4A1AE826-FB78-4DD3-881...,8,11,5568,43114,0.129146
82569,esca,TCGA-JY-A6FA-01Z-00-DX1.F23F28C7-5514-4696-8CA...,8,11,63,3980,0.015829
82754,esca,TCGA-LN-A49V-01Z-00-DX1.FD93D99F-F318-4D08-9E0...,8,11,1110,16159,0.068692
83520,esca,TCGA-IG-A4QS-01Z-00-DX1.4B51BDD5-31F8-48E4-BF1...,8,11,12518,78487,0.159491
84066,esca,TCGA-IG-A3YA-01Z-00-DX1.C2A7B316-44E0-4CA3-B76...,8,11,9745,41970,0.232190
84389,esca,TCGA-S8-A6BV-01Z-00-DX1.F9237F35-CEFE-4F00-83F...,8,11,5,112,0.044643
85091,esca,TCGA-LN-A5U5-01Z-00-DX1.750F8DA5-7A2C-44EB-856...,8,11,6,2024,0.002964
85293,esca,TCGA-V5-A7RC-01Z-00-DX1.044C13B6-A5D9-4DBB-BD0...,8,11,34,508,0.066929
86573,esca,TCGA-JY-A93C-01Z-00-DX1.5827ADD2-796F-4CC1-AEB...,8,11,14541,30255,0.480615
86909,esca,TCGA-IG-A5B8-01Z-00-DX1.3FC85163-3C6F-4D39-A0E...,8,11,27,8100,0.003333
87242,esca,TCGA-IG-A7DP-01Z-00-DX1.81A5A30F-6979-4DC1-A2D...,8,11,387,37859,0.010222
87547,esca,TCGA-IG-A6QS-01Z-00-DX1.F8F804CA-97FA-4941-BB0...,8,11,23,28203,0.000816
89420,esca,TCGA-LN-A49K-01Z-00-DX1.CCD96BF7-8659-4B4E-86B...,8,11,1,568,0.001761
90258,esca,TCGA-IG-A3QL-01Z-00-DX1.D7C07E36-F35B-4369-A21...,8,11,247,7623,0.032402
90797,esca,TCGA-IG-A3YC-01Z-00-DX1.71785237-8DA6-4034-9CD...,8,11,813,60344,0.013473
91071,esca,TCGA-IG-A8O2-01Z-00-DX1.FABD0323-82D9-44F2-87B...,8,11,9450,31941,0.295858
91412,esca,TCGA-S8-A6BW-01Z-00-DX1.3DD9D2C3-73C9-4B9C-949...,8,11,1,765,0.001307
91606,esca,TCGA-JY-A93D-01Z-00-DX1.14D17584-237D-4197-AC5...,8,11,7441,31278,0.237899
92036,esca,TCGA-L5-A4OX-01Z-00-DX1.44575F16-A28B-4865-BAF...,8,11,11,204,0.053922
94152,esca,TCGA-IG-A97H-01Z-00-DX1.DB5FAE75-4F0D-4D25-BE6...,8,11,59,70682,0.000835
94679,esca,TCGA-JY-A6FH-01Z-00-DX1.4065B89C-528B-4D3A-BBE...,8,11,12641,28952,0.436619
96030,esca,TCGA-IG-A4P3-01Z-00-DX1.C470B2B7-F55E-4E0C-A7E...,8,11,151,28510,0.005296
96853,esca,TCGA-JY-A6F8-01Z-00-DX1.0AA9B993-9DFA-431D-9FA...,8,11,1312,2952,0.444444
97554,esca,TCGA-L5-A4OJ-01Z-00-DX1.585AE027-2DE4-433C-B7B...,8,11,1,268,0.003731
98716,esca,TCGA-IG-A3Y9-01Z-00-DX1.830A7D80-F4B1-4A78-B55...,8,11,1700,31733,0.053572
98858,esca,TCGA-JY-A6FB-01Z-00-DX1.8BCAB739-0AEE-41C1-B45...,8,11,13273,26758,0.496039
99072,esca,TCGA-JY-A939-01Z-00-DX1.BD1BA160-929F-442B-808...,8,11,2362,5353,0.441248
100721,esca,TCGA-IG-A97I-01Z-00-DX1.3C27B8C0-A346-4B05-98E...,8,11,23,2509,0.009167
100994,esca,TCGA-IG-A51D-01Z-00-DX1.46951C8F-2583-4511-8A6...,8,11,8068,55963,0.144167
101609,esca,TCGA-IG-A3I8-01Z-00-DX1.00D0CD6B-06E7-4F3B-BD2...,8,11,19711,42385,0.465047
102925,esca,TCGA-LN-A4MQ-01Z-00-DX1.72CA5EC0-771F-4A7B-900...,8,11,11,539,0.020408
103275,esca,TCGA-IG-A5S3-01Z-00-DX1.2410F826-855B-41CD-ADC...,8,11,386,19922,0.019376
103589,esca,TCGA-RE-A7BO-01Z-00-DX1.E6F76917-D416-420D-A3A...,8,11,1766,45962,0.038423
104082,esca,TCGA-L5-A4OP-01Z-00-DX1.D56B7379-2BC1-459A-90A...,8,11,1,32,0.031250
106749,esca,TCGA-JY-A6FD-01Z-00-DX1.9AD5430C-5B26-44F0-82F...,8,11,18,21017,0.000856

In [78]:
sorted_df = filtered_df.sort_values(by=['contact count'], ascending=False)
sorted_df

,cancer_type,tcga_id,cluster 1,cluster 2,contact count,total_c1_interactions,frequency
101609,esca,TCGA-IG-A3I8-01Z-00-DX1.00D0CD6B-06E7-4F3B-BD2...,8,11,19711,42385,0.465047
80917,esca,TCGA-JY-A93E-01Z-00-DX1.ECCA983B-C9EE-4074-A28...,8,11,14944,42278,0.353470
86573,esca,TCGA-JY-A93C-01Z-00-DX1.5827ADD2-796F-4CC1-AEB...,8,11,14541,30255,0.480615
98858,esca,TCGA-JY-A6FB-01Z-00-DX1.8BCAB739-0AEE-41C1-B45...,8,11,13273,26758,0.496039
94679,esca,TCGA-JY-A6FH-01Z-00-DX1.4065B89C-528B-4D3A-BBE...,8,11,12641,28952,0.436619
83520,esca,TCGA-IG-A4QS-01Z-00-DX1.4B51BDD5-31F8-48E4-BF1...,8,11,12518,78487,0.159491
84066,esca,TCGA-IG-A3YA-01Z-00-DX1.C2A7B316-44E0-4CA3-B76...,8,11,9745,41970,0.232190
91071,esca,TCGA-IG-A8O2-01Z-00-DX1.FABD0323-82D9-44F2-87B...,8,11,9450,31941,0.295858
100994,esca,TCGA-IG-A51D-01Z-00-DX1.46951C8F-2583-4511-8A6...,8,11,8068,55963,0.144167
91606,esca,TCGA-JY-A93D-01Z-00-DX1.14D17584-237D-4197-AC5...,8,11,7441,31278,0.237899
81532,esca,TCGA-ZR-A9CJ-01Z-00-DX1.4A1AE826-FB78-4DD3-881...,8,11,5568,43114,0.129146
78065,esca,TCGA-IG-A625-01Z-00-DX1.48DC96DA-6573-4AA3-898...,8,11,2487,38355,0.064842
99072,esca,TCGA-JY-A939-01Z-00-DX1.BD1BA160-929F-442B-808...,8,11,2362,5353,0.441248
103589,esca,TCGA-RE-A7BO-01Z-00-DX1.E6F76917-D416-420D-A3A...,8,11,1766,45962,0.038423
98716,esca,TCGA-IG-A3Y9-01Z-00-DX1.830A7D80-F4B1-4A78-B55...,8,11,1700,31733,0.053572
79448,esca,TCGA-IG-A50L-01Z-00-DX1.25755523-4D42-4377-B05...,8,11,1362,38037,0.035807
96853,esca,TCGA-JY-A6F8-01Z-00-DX1.0AA9B993-9DFA-431D-9FA...,8,11,1312,2952,0.444444
82754,esca,TCGA-LN-A49V-01Z-00-DX1.FD93D99F-F318-4D08-9E0...,8,11,1110,16159,0.068692
90797,esca,TCGA-IG-A3YC-01Z-00-DX1.71785237-8DA6-4034-9CD...,8,11,813,60344,0.013473
87242,esca,TCGA-IG-A7DP-01Z-00-DX1.81A5A30F-6979-4DC1-A2D...,8,11,387,37859,0.010222
103275,esca,TCGA-IG-A5S3-01Z-00-DX1.2410F826-855B-41CD-ADC...,8,11,386,19922,0.019376
90258,esca,TCGA-IG-A3QL-01Z-00-DX1.D7C07E36-F35B-4369-A21...,8,11,247,7623,0.032402
96030,esca,TCGA-IG-A4P3-01Z-00-DX1.C470B2B7-F55E-4E0C-A7E...,8,11,151,28510,0.005296
82569,esca,TCGA-JY-A6FA-01Z-00-DX1.F23F28C7-5514-4696-8CA...,8,11,63,3980,0.015829
94152,esca,TCGA-IG-A97H-01Z-00-DX1.DB5FAE75-4F0D-4D25-BE6...,8,11,59,70682,0.000835
85293,esca,TCGA-V5-A7RC-01Z-00-DX1.044C13B6-A5D9-4DBB-BD0...,8,11,34,508,0.066929
78742,esca,TCGA-JY-A93F-01Z-00-DX1.8DCF766B-0B3F-4B4C-8FD...,8,11,29,16766,0.001730
86909,esca,TCGA-IG-A5B8-01Z-00-DX1.3FC85163-3C6F-4D39-A0E...,8,11,27,8100,0.003333
100721,esca,TCGA-IG-A97I-01Z-00-DX1.3C27B8C0-A346-4B05-98E...,8,11,23,2509,0.009167
87547,esca,TCGA-IG-A6QS-01Z-00-DX1.F8F804CA-97FA-4941-BB0...,8,11,23,28203,0.000816
106749,esca,TCGA-JY-A6FD-01Z-00-DX1.9AD5430C-5B26-44F0-82F...,8,11,18,21017,0.000856
92036,esca,TCGA-L5-A4OX-01Z-00-DX1.44575F16-A28B-4865-BAF...,8,11,11,204,0.053922
102925,esca,TCGA-LN-A4MQ-01Z-00-DX1.72CA5EC0-771F-4A7B-900...,8,11,11,539,0.020408
85091,esca,TCGA-LN-A5U5-01Z-00-DX1.750F8DA5-7A2C-44EB-856...,8,11,6,2024,0.002964
84389,esca,TCGA-S8-A6BV-01Z-00-DX1.F9237F35-CEFE-4F00-83F...,8,11,5,112,0.044643
80155,esca,TCGA-LN-A49M-01Z-00-DX1.3D8240BD-2689-4CBB-83E...,8,11,2,432,0.004630
91412,esca,TCGA-S8-A6BW-01Z-00-DX1.3DD9D2C3-73C9-4B9C-949...,8,11,1,765,0.001307
89420,esca,TCGA-LN-A49K-01Z-00-DX1.CCD96BF7-8659-4B4E-86B...,8,11,1,568,0.001761
97554,esca,TCGA-L5-A4OJ-01Z-00-DX1.585AE027-2DE4-433C-B7B...,8,11,1,268,0.003731
104082,esca,TCGA-L5-A4OP-01Z-00-DX1.D56B7379-2BC1-459A-90A...,8,11,1,32,0.031250

In [79]:
sorted_df['tcga_id'].to_list()[:10]

['TCGA-IG-A3I8-01Z-00-DX1.00D0CD6B-06E7-4F3B-BD24-2E18DE926045',
 'TCGA-JY-A93E-01Z-00-DX1.ECCA983B-C9EE-4074-A288-A35129C0E0EB',
 'TCGA-JY-A93C-01Z-00-DX1.5827ADD2-796F-4CC1-AEBA-B87FDF529FC6',
 'TCGA-JY-A6FB-01Z-00-DX1.8BCAB739-0AEE-41C1-B45B-07C615677DBB',
 'TCGA-JY-A6FH-01Z-00-DX1.4065B89C-528B-4D3A-BBE1-81DFE5BD1F4C',
 'TCGA-IG-A4QS-01Z-00-DX1.4B51BDD5-31F8-48E4-BF1D-A2C66A1B11C3',
 'TCGA-IG-A3YA-01Z-00-DX1.C2A7B316-44E0-4CA3-B76A-241C61BFE492',
 'TCGA-IG-A8O2-01Z-00-DX1.FABD0323-82D9-44F2-87B5-E5A93FEB64DE',
 'TCGA-IG-A51D-01Z-00-DX1.46951C8F-2583-4511-8A6E-E815F5EED0BC',
 'TCGA-JY-A93D-01Z-00-DX1.14D17584-237D-4197-AC50-F8293D576445']

In [55]:
slide_id = "TCGA-US-A77J-01Z-00-DX1.72AE50D3-F776-4000-B6B0-C64194AB549F"
sample_df = filtered_df[filtered_df['tcga_id'] == slide_id]
sample_df

Empty DataFrame
Columns: [cancer_type, tcga_id, cluster 1, cluster 2, contact count, total_c1_interactions, frequency]
Index: []