In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from tqdm.notebook import tqdm

In [9]:
labelled_data = pd.read_pickle('pkl/GI_cluster50_labelled_all_mar28.pkl') #dataframe containing the cluster labels for each coordinate 
labelled_data.head()

                                                          label     X      Y
paad TCGA-HZ-A9TJ-01Z-00-DX1.CB2953B6-9601-4300-BC89... 0     0  1792  11264
                                                        1     0  1792  11520
                                                        2    46  2048   9984
                                                        3    46  2048  10240
                                                        4    46  2048  10496

In [4]:
pairwise_slide = pd.read_pickle('pkl/cluster_50_pairwise_slide_04_06_26.pkl') 
pairwise_slide.head()

,cancer_type,tcga_id,cluster 1,cluster 2,contact count,total cluster 1,total cluster 2,total_c1_interactions,frequency
0,coad,TCGA-AA-3553-01Z-00-DX1.45a24cd4-6eb2-4f20-945...,3,4,8825,4126,3722,30362,0.290659
1,coad,TCGA-AA-3553-01Z-00-DX1.45a24cd4-6eb2-4f20-945...,3,34,543,4126,129,30362,0.017884
2,coad,TCGA-AA-3553-01Z-00-DX1.45a24cd4-6eb2-4f20-945...,4,34,108,3722,129,29409,0.003672
3,coad,TCGA-AA-3695-01Z-00-DX1.be93a101-7b57-4140-bd8...,3,4,16012,7085,13341,54786,0.292264
4,coad,TCGA-AA-3695-01Z-00-DX1.be93a101-7b57-4140-bd8...,3,13,8,7085,1,54786,0.000146

In [5]:
pairwise_freq = pd.read_pickle('pkl/cluster_50_freq.pkl') 
pairwise_freq.head()

label,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
tcga_id,,,,,,,,,,,,,,,,,,,,,
TCGA-05-4244-01Z-00-DX1.d4ff32cd-38cf-40ea-8213-45c2b100ac01,0.0,0.000000,0.000434,0.626020,0.297290,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.009727,0.0,0.021626,0.001042,0.000000,0.0
TCGA-05-4245-01Z-00-DX1.36ff5403-d4bb-4415-b2c5-7c750d655cde,0.0,0.000256,0.060548,0.484639,0.302867,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.018689,0.0,0.016641,0.000128,0.003840,0.0
TCGA-05-4249-01Z-00-DX1.9fce0297-cc19-4c04-872c-4466ee4024db,0.0,0.000000,0.000307,0.712273,0.119353,0.0,0.000256,0.0,0.0,0.0,...,0.0,0.000000,0.000051,0.0,0.000000,0.0,0.016136,0.000051,0.002356,0.0
TCGA-05-4250-01Z-00-DX1.90f67fdf-dff9-46ca-af71-0978d7c221ba,0.0,0.000065,0.001821,0.581686,0.319199,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000065,0.000000,0.0,0.000260,0.0,0.010731,0.000976,0.000976,0.0
TCGA-05-4382-01Z-00-DX1.76b49a4c-dbbb-48b0-b677-6d3037e5ce88,0.0,0.000551,0.001652,0.648234,0.182333,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000079,0.000000,0.0,0.004248,0.0,0.047589,0.005192,0.000315,0.0

In [6]:
labelled_data = labelled_data.loc[['esca','coad','paad','stad','read']]
labelled_data

                                                              label      X  \
esca TCGA-2H-A9GF-01Z-00-DX1.FA1016AF-3FE3-45DC-A77B... 0        13   4352
                                                        1        32   4352
                                                        2        32   4352
                                                        3        47   4608
                                                        4        48   4608
...                                                             ...    ...
read TCGA-F5-6861-01Z-00-DX1.011B771B-F52E-412E-9352... 36609    13  94208
                                                        36610    29  94208
                                                        36611    29  94208
                                                        36612    13  94208
                                                        36613    13  94208

                                                                   Y
esca TCGA-2H-A9GF-01Z-00-DX1.FA1016AF-3FE3-45DC-A77B... 0      63232
                                                        1      63488
                                                        2      63744
                                                        3      61952
                                                        4      62208
...                                                              ...
read TCGA-F5-6861-01Z-00-DX1.011B771B-F52E-412E-9352... 36609  20736
                                                        36610  20992
                                                        36611  21248
                                                        36612  21504
                                                        36613  21760

[58780353 rows x 3 columns]

In [7]:
all_slide_ids = pd.read_pickle('pkl/GI_allslide_IDs_mar28.pkl') #dataframe with all the slide IDs 
cancer_types = ['paad','coad','esca','stad','read']
all_slide_ids

paad  0      TCGA-HZ-A9TJ-01Z-00-DX1.CB2953B6-9601-4300-BC8...
      1      TCGA-IB-A5SP-01Z-00-DX1.0D3C9A7E-F73C-4F03-98C...
      2      TCGA-2L-AAQL-01Z-00-DX1.641D4EA1-ABC9-4121-BB2...
      3      TCGA-HV-A7OP-01Z-00-DX1.9DCA3D26-8093-4D09-AE2...
      4      TCGA-2L-AAQE-01Z-00-DX1.5D60E31B-9E39-4472-837...
                                   ...
read  153    TCGA-AG-4007-01Z-00-DX1.1344292e-78ad-4db8-b03...
      154    TCGA-F5-6864-01Z-00-DX1.95556dfa-18a9-4a59-a1f...
      155    TCGA-AG-4001-01Z-00-DX1.1dbafe58-de6b-47a0-9b4...
      156    TCGA-G5-6641-01Z-00-DX1.5d9d937f-0e87-4cdb-87f...
      157    TCGA-F5-6861-01Z-00-DX1.011B771B-F52E-412E-935...
Length: 1841, dtype: object

In [8]:
short_ids = all_slide_ids.str[:12] 
short_ids

paad  0      TCGA-HZ-A9TJ
      1      TCGA-IB-A5SP
      2      TCGA-2L-AAQL
      3      TCGA-HV-A7OP
      4      TCGA-2L-AAQE
                 ...
read  153    TCGA-AG-4007
      154    TCGA-F5-6864
      155    TCGA-AG-4001
      156    TCGA-G5-6641
      157    TCGA-F5-6861
Length: 1841, dtype: object

In [89]:
cancer_type = 'coad'
cancer_type_list = ['coad', 'esca', 'paad', 'stad', 'read'] 
cn_1 = 17

In [90]:
filtered_df = pairwise_slide[(pairwise_slide['cancer_type']==cancer_type) & (pairwise_slide['cluster 1']==cn_1)] #return dataframe for the cluster pair of interest 
filtered_df

,cancer_type,tcga_id,cluster 1,cluster 2,contact count,total cluster 1,total cluster 2,total_c1_interactions,frequency
13,coad,TCGA-AA-3695-01Z-00-DX1.be93a101-7b57-4140-bd8...,17,36,1,1,1,8,0.125000
148,coad,TCGA-D5-6535-01Z-00-DX1.0d7485ff-cf98-4c86-8a6...,17,19,7,315,645,2520,0.002778
149,coad,TCGA-D5-6535-01Z-00-DX1.0d7485ff-cf98-4c86-8a6...,17,22,1,315,4,2520,0.000397
150,coad,TCGA-D5-6535-01Z-00-DX1.0d7485ff-cf98-4c86-8a6...,17,23,1198,315,11454,2520,0.475397
151,coad,TCGA-D5-6535-01Z-00-DX1.0d7485ff-cf98-4c86-8a6...,17,24,2,315,245,2520,0.000794
...,...,...,...,...,...,...,...,...,...
76875,coad,TCGA-CM-6675-01Z-00-DX1.4f2301e2-2894-484d-8a5...,17,36,999,551,16779,4406,0.226736
76876,coad,TCGA-CM-6675-01Z-00-DX1.4f2301e2-2894-484d-8a5...,17,38,15,551,2747,4406,0.003404
76877,coad,TCGA-CM-6675-01Z-00-DX1.4f2301e2-2894-484d-8a5...,17,42,2,551,417,4406,0.000454
76878,coad,TCGA-CM-6675-01Z-00-DX1.4f2301e2-2894-484d-8a5...,17,46,47,551,2451,4406,0.010667
76879,coad,TCGA-CM-6675-01Z-00-DX1.4f2301e2-2894-484d-8a5...,17,47,1,551,2749,4406,0.000227

In [91]:
sorted_df = filtered_df.sort_values(by=['total cluster 1'], ascending=False)
sorted_df

,cancer_type,tcga_id,cluster 1,cluster 2,contact count,total cluster 1,total cluster 2,total_c1_interactions,frequency
53208,coad,TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B04...,17,48,102,20416,184,163100,0.000625
53198,coad,TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B04...,17,35,76,20416,217,163100,0.000466
53196,coad,TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B04...,17,29,30,20416,23,163100,0.000184
53199,coad,TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B04...,17,36,104,20416,21,163100,0.000638
53197,coad,TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B04...,17,33,106,20416,69,163100,0.000650
...,...,...,...,...,...,...,...,...,...
8699,coad,TCGA-A6-A566-01Z-00-DX1.325BC1B7-2D0D-43CC-A23...,17,46,1,1,3830,8,0.125000
37851,coad,TCGA-A6-A5ZU-01Z-00-DX1.8E7A136C-46C4-4233-A74...,17,42,1,1,265,8,0.125000
510,coad,TCGA-D5-6931-01Z-00-DX1.c1d00654-b5ff-4485-90a...,17,19,6,1,15849,8,0.750000
511,coad,TCGA-D5-6931-01Z-00-DX1.c1d00654-b5ff-4485-90a...,17,23,2,1,2946,8,0.250000
13,coad,TCGA-AA-3695-01Z-00-DX1.be93a101-7b57-4140-bd8...,17,36,1,1,1,8,0.125000

In [92]:
sorted_df['tcga_id'].to_list()[:10]

['TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0',
 'TCGA-DM-A1DB-01Z-00-DX1.092D3ABD-7DFE-4193-B049-B3C3617706B0']

In [45]:
slide_id = "TCGA-US-A77J-01Z-00-DX1.72AE50D3-F776-4000-B6B0-C64194AB549F"
sample_df = filtered_df[filtered_df['tcga_id'] == slide_id]
sample_df

Empty DataFrame
Columns: [cancer_type, tcga_id, cluster 1, cluster 2, contact count, total cluster 1, total cluster 2, total_c1_interactions, frequency]
Index: []